export default [
    {
        label: '单行输入',
        icon: '&#xe692;',
        name: 'input'
    }, {
        label: '多行输入',
        icon: '&#xe693;'
    }, {
        label: '计数器',
        icon: '&#xe7f3;'
    }, {
        label: '单选项',
        icon: '&#xe71f;'
    }, {
        label: '多选项',
        icon: '&#xeb5f;'
    }, {
        label: '下拉选项',
        icon: '&#xe62e;'
    }, {
        label: '时间',
        icon: '&#xe64d;'
    }, {
        label: '时间范围',
        icon: '&#xe602;'
    }, {
        label: '日期',
        icon: '&#xe660;'
    }, {
        label: '日期范围',
        icon: '&#xeb3f;'
    }, {
        label: '开关',
        icon: '&#xeb98;'
    }, {
        label: '评分',
        icon: '&#xe69d;'
    }, {
        label: '颜色选择器',
        icon: '&#xe67e;'
    }, {
        label: '滑块',
        icon: '&#xe606;'
    }, {
        label: '静态文字',
        icon: '&#xe611;'
    }, {
        label: 'html',
        icon: '&#xe7ae;'
    }, {
        label: '按钮',
        icon: '&#xeb95;'
    }, {
        label: '分割线',
        icon: '&#xe646;'
    },
]
